

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/productcatalog?createDatabaseIfNotExist=True
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  application:
    name: product-catalog

  cloud:
    config:
      uri: http://localhost:8888